language: d
dist: xenial
sudo: false

matrix:
  include:
    - d: dmd
    - d: dmd-2.088.0
    - d: dmd-2.087.1
    - d: dmd-2.086.1
    - d: ldc
    - d: ldc-1.17.0
    - d: ldc-1.16.0
    - d: ldc-1.15.0
    - d: ldc-1.14.0

addons:
  apt:
    packages:
      - libzmq3-dev

script:
  - dub test --build=unittest-cov --compiler=${DC}

after_success:
 - bash <(curl -s https://codecov.io/bash)
